port: 9361
# private_key:
# certificate:
db_connection: >-
  host=puffer-dev.c78hjwwa209d.us-west-1.rds.amazonaws.com port=5432
  dbname=puffer user=puffer
log_dir: # change this to a desired folder for logging
channel:
  - fox
fox:
  live: true
  input: media/fox/
  video:
    1280x720: [23, 28]
  audio:
    - 128k
