port: 8081
max_buffer_s: 30
max_inflight_s: 10
max_ws_frame_b: 1000000
max_ws_queue_b: 10000000
channel:
  - tos
  - tos-live
tos:
  live: false
  input: tos/
  video:
    1280x720: [20, 28]
    854x480: [20, 28]
  audio:
    - 128k
  timescale: 90000
  video_duration: 180000
  audio_duration: 432000
  video_codec: 'video/mp4; codecs="avc1.42E020"'
  audio_codec: 'audio/webm; codecs="opus"'
  init_vts: 0
tos-live:
  live: true
  input: tos-live/
  video:
    1280x720: [20, 28]
    854x480: [20, 28]
  audio:
    - 128k
  timescale: 90000
  video_duration: 180000
  audio_duration: 432000
  video_codec: 'video/mp4; codecs="avc1.42E020"'
  audio_codec: 'audio/webm; codecs="opus"'
  presentation_delay_s: 10
  clean_window_s: 60
