[package]
name = "ccp_interface"
version = "0.1.0"
authors = ["Puffer authors"]
edition = "2018"

[dependencies]
portus = { git = "https://github.com/StanfordSNR/portus" }
clap="2.29"
slog = "2"
slog-async = "2"
slog-term = "2"
time="0.1"
